name: Build and Deploy on Local Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the app on your local server via SSH
      - name: Build on local server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          # key: ${{ secrets.SERVER_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 40473  # Port given by Ngrok
          script: |
            # Ensure Node.js is in PATH
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # Load nvm
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # Load nvm bash_completion (optional)

            # Go to your app directory
            cd /home/mena/Desktop/health-line/

            # Pull the latest code from the repo
            git pull

            # Verify Node.js version
            node -v

            # Build the app
            # npm install
            npm run build
