name: Build and Deploy on Local Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the app on your local server via SSH
      - name: Build on local server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 43297  # Port given by Ngrok
          script: |
            # Go to your app directory
            cd /home/mena/Desktop/health-line/

            # Pull the latest code from the repo
            git reset --hard
            git pull origin main


            npm run build
